name: au10tix_flutter
description: A new flutter plugin for adding native Au10tix SDK.
version: 0.0.1
homepage: https://github.com/Fondeadora/au10tix-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: 1.22.5
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fondeadora.au10tix_flutter
        pluginClass: Au10tixFlutterPlugin
      ios:
        pluginClass: Au10tixFlutterPlugin
